spring.application.name=microservice-clientUI

server.port=8110

################### Eureka Configuration ##########################
eureka.client.serviceUrl.defaultZone: http://eureka-server:9102/eureka/

feign.client.url.microservice-gateway=http://microservice-gateway:8080