spring.application.name=microservice-diabet-assessment
server.port=8112

################### Eureka Configuration ##########################
eureka.client.serviceUrl.defaultZone: http://eureka-server:9102/eureka/

feign.client.url.microservice-gateway=http://microservice-gateway:8080