spring.application.name=microservice-diabet-assessment
server.port=8112

################### Eureka Configuration ##########################
eureka.client.serviceUrl.defaultZone: http://localhost:9102/eureka/

feign.client.url.microservice-gateway=http://localhost:8080

spring.main.allow-bean-definition-overriding=true