spring.application.name=microservice-notes
server.port=8111


################### DataSource Configuration ##########################
spring.data.mongodb.host=host.docker.internal
spring.data.mongodb.port=27017
spring.data.mongodb.database=medilabo

spring.data.mongodb.username=microservice
spring.data.mongodb.password=microservice

################### MongoDB Driver ##########################
logging.level.org.mongodb.driver=DEBUG

################### Eureka Configuration ##########################
eureka.client.serviceUrl.defaultZone: http://eureka-server:9102/eureka/