spring.application.name=microservice-notes
server.port=8111


################### DataSource Configuration ##########################
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=medilabo

spring.data.mongodb.username=microservice
spring.data.mongodb.password=microservice

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.springframework.data.mongodb.core.MongoDbUtils=DEBUG
#logging.level.org.mongodb.driver=DEBUG

################### Eureka Configuration ##########################
eureka.client.serviceUrl.defaultZone: http://localhost:9102/eureka/