spring.application.name=gateway
server.port=8080
spring.main.web-application-type=reactive
#logging.level.org.springframework=DEBUG

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.server=DEBUG


# Route pour le service "clientUI"
spring.cloud.gateway.routes[0].id=ClientUI
spring.cloud.gateway.routes[0].uri=http://localhost:8110
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**